---
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    image: adventure-api:latest
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    networks:
      - adventure
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:17-alpine
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5434:5432"
    networks:
      - adventure
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

networks:
  adventure:
    driver: bridge

volumes:
  postgres-data:
