FROM python:3.12-slim-bookworm

# Update OS packages and remove cache to reduce image size
RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Install uv
RUN pip install --no-cache-dir uv

# Copy & install dependencies
COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev --system

COPY . .

RUN chmod +x entrypoint.sh

EXPOSE 5000

CMD ["./entrypoint.sh"]
